apiVersion: v1
kind: Service
metadata:
  name: nodeapi
  namespace: hurb
spec:
  type: NodePort
  ports:
    - nodePort: 31318
      port: 8888
      protocol: TCP
      targetPort: 8888
  selector:
    app: nodeapi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapi
  namespace: hurb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapi
  template:
    metadata:
      labels:
        app: nodeapi
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nodeapi 
        image: cezarfw/app-desafio:latest 
        resources:
          requests:
            memory: "512Mi"
        ports:
        - containerPort: 8888
          name: nodeapi
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: mysql-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: mysql-password
