apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: hurb
spec:
  type: NodePort
  ports:
    - nodePort: 80
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: hurb
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
          - name: config-nginx-volume
            mountPath: /etc/nginx
      volumes:
      - name: config-nginx-volume
        configMap:
          name: nginx-config
